import { Router } from 'express';
import { makeAddRatingController } from '../factories/add-rating-factory';
import { adaptRoute } from '@/bin/configuration/adapters/express-route-adapter';
import { makeLoadRatingsController } from '../factories/load-rating-factory';
import { adminAuth } from '@/bin/middlewares/admin-auth';
import { auth } from '@/bin/middlewares/auth';
const router = Router();
router.post('/', adminAuth, adaptRoute(makeAddRatingController()));
router.get('/', auth, adaptRoute(makeLoadRatingsController()));
export default router;
