import { Router } from 'express';
import { makeSignUpController } from '../factories/signup-factory';
import { adaptRoute } from '@/bin/configuration/adapters/express-route-adapter';
import { makeLoginController } from '../factories/login-factory';
import { makeLoadAccountByPageController } from '../factories/load-account-by-page-factory';
import { auth } from '@/bin/middlewares/auth';
const router = Router();
router.post('/signup', adaptRoute(makeSignUpController()));
router.post('/login', adaptRoute(makeLoginController()));
router.get('/page/:page', auth, adaptRoute(makeLoadAccountByPageController()));
export default router;
