import { Router } from 'express';
import { makeAddRatingController } from '../factories/add-rating-factory';
import { adaptRoute } from '../../../bin/configuration/adapters/express-route-adapter';
import { makeAuthMiddleware } from '../../../bin/patterns/factories/middlewares/auth-middleware-factory';
import { adaptMiddleware } from '../../../bin/configuration/adapters/express-middleware-adapter';
import { makeLoadRatingsController } from '../factories/load-rating-factory';
const router = Router();
const adminAuth = adaptMiddleware(makeAuthMiddleware('admin'));
const auth = adaptMiddleware(makeAuthMiddleware());
router.post('/', adminAuth, adaptRoute(makeAddRatingController()));
router.get('/', auth, adaptRoute(makeLoadRatingsController()));
export default router;
